Примеры тестовых данных

In [ ]:
users = [
    {
        "id": 1,
        "name" : "test1",
        "country" : "Russia"
    },
     {
        "id": 2,
        "name" : "test2",
        "country" : "Russia"
    },
     {
        "id": 3,
        "name" :  "test3",
        "country" : "Finland"
    },
     {
        "id": 4,
        "name" : "test4",
        "country" : "Germany"
    }
]

In [ ]:
apps = [
    {
        "id": 0,
        "name": "birds"
    },
     {
        "id": 1,
        "name": "cats"
    },
     {
        "id": 2,
        "name": "dogs"
    },
     {
        "id": 3,
        "name": "wtf???"
    }
]

In [ ]:
stats = [
    {
        "user_id": 1,
        "app_id" : 0,
        "date_begin": "2023-03-21 15:00:00",
        "date_end": "2023-03-21 18:00:00"
    },
     {
        "user_id": 1,
        "app_id" : 0,
        "date_begin": "2023-03-21 20:00:00",
        "date_end": "2023-03-21 21:00:00"
    },
     {
        "user_id": 1,
        "app_id" : 0,
        "date_begin": "2023-03-22 15:00:00",
        "date_end": "2023-03-22 21:00:00"
    },
     {
        "user_id": 1,
        "app_id" : 1,
        "date_begin": "2023-03-21 12:00:00",
        "date_end": "2023-03-21 13:00:00"
    },
     {
        "user_id": 1,
        "app_id" : 1,
        "date_begin": "2023-03-24 19:00:00",
        "date_end": "2023-03-24 21:00:00"
    },
     {
        "user_id": 2,
        "app_id" : 3,
        "date_begin": "2023-03-03 15:00:00",
        "date_end": "2023-03-03 16:00:00"
    },
     {
        "user_id": 2,
        "app_id" : 3,
        "date_begin": "2023-03-04 19:00:00",
        "date_end": "2023-03-04 20:00:00"
    },


]

In [ ]:
import pandas as pd

Преобразуем в датавреймы

In [ ]:
df_users = pd.DataFrame(users)

In [ ]:
df_users.set_index("id")

     name  country
id
1   test1   Russia
2   test2   Russia
3   test3  Finland
4   test4  Germany

In [ ]:
df_apps = pd.DataFrame(apps)

In [ ]:
df_apps.set_index("id")

      name
id
0    birds
1     cats
2     dogs
3   wtf???

In [ ]:
df_stats = pd.DataFrame(stats)

Преобразуем поле с датой/временем в дату

In [ ]:
# если загружаем с .csv

# data = pd.read_csv('your_dataset.csv', parse_dates=['date_begin',"date_end" ])

# если уже есть DataFrame

df_stats['date_begin'] = pd.to_datetime(df_stats['date_begin'])
df_stats['date_end'] = pd.to_datetime(df_stats['date_end'])

In [ ]:
df_stats

   user_id  app_id          date_begin            date_end
0        1       0 2023-03-21 15:00:00 2023-03-21 18:00:00
1        1       0 2023-03-21 20:00:00 2023-03-21 21:00:00
2        1       0 2023-03-22 15:00:00 2023-03-22 21:00:00
3        1       1 2023-03-21 12:00:00 2023-03-21 13:00:00
4        1       1 2023-03-24 19:00:00 2023-03-24 21:00:00
5        2       3 2023-03-03 15:00:00 2023-03-03 16:00:00
6        2       3 2023-03-04 19:00:00 2023-03-04 20:00:00

Далее выделим из даты отдельно день, месяц, год и время

Для удобства завернем все в цикл

In [ ]:
labels = ["date_begin", "date_end"]

for label in labels:
  df_stats[label+'_year'] = pd.to_datetime(df_stats[label]).dt.year
  df_stats[label+'_month'] = pd.to_datetime(df_stats[label]).dt.month
  df_stats[label+'_day'] = pd.to_datetime(df_stats[label]).dt.day

In [ ]:
df_stats

,user_id,app_id,date_begin,date_end,date_begin_year,date_begin_month,date_begin_day,date_end_year,date_end_month,date_end_day
0,1,0,2023-03-21 15:00:00,2023-03-21 18:00:00,2023,3,21,2023,3,21
1,1,0,2023-03-21 20:00:00,2023-03-21 21:00:00,2023,3,21,2023,3,21
2,1,0,2023-03-22 15:00:00,2023-03-22 21:00:00,2023,3,22,2023,3,22
3,1,1,2023-03-21 12:00:00,2023-03-21 13:00:00,2023,3,21,2023,3,21
4,1,1,2023-03-24 19:00:00,2023-03-24 21:00:00,2023,3,24,2023,3,24
5,2,3,2023-03-03 15:00:00,2023-03-03 16:00:00,2023,3,3,2023,3,3
6,2,3,2023-03-04 19:00:00,2023-03-04 20:00:00,2023,3,4,2023,3,4

### Объединяем данные

In [ ]:
merged_df = pd.merge(df_stats, df_users, left_on='user_id', right_on='id')

In [ ]:
merged_df

,user_id,app_id,date_begin,date_end,date_begin_year,date_begin_month,date_begin_day,date_end_year,date_end_month,date_end_day,id,name,country
0,1,0,2023-03-21 15:00:00,2023-03-21 18:00:00,2023,3,21,2023,3,21,1,test1,Russia
1,1,0,2023-03-21 20:00:00,2023-03-21 21:00:00,2023,3,21,2023,3,21,1,test1,Russia
2,1,0,2023-03-22 15:00:00,2023-03-22 21:00:00,2023,3,22,2023,3,22,1,test1,Russia
3,1,1,2023-03-21 12:00:00,2023-03-21 13:00:00,2023,3,21,2023,3,21,1,test1,Russia
4,1,1,2023-03-24 19:00:00,2023-03-24 21:00:00,2023,3,24,2023,3,24,1,test1,Russia
5,2,3,2023-03-03 15:00:00,2023-03-03 16:00:00,2023,3,3,2023,3,3,2,test2,Russia
6,2,3,2023-03-04 19:00:00,2023-03-04 20:00:00,2023,3,4,2023,3,4,2,test2,Russia

Удалим id пользователей, вряд ли будут дальше нужны

In [ ]:
merged_df.drop('user_id', axis=1, inplace=True)

И аналогично для приложений

In [ ]:
merged_df = pd.merge(df_stats, df_apps, left_on='app_id', right_on='id')

In [ ]:
merged_df

,user_id,app_id,date_begin,date_end,date_begin_year,date_begin_month,date_begin_day,date_end_year,date_end_month,date_end_day,id,name
0,1,0,2023-03-21 15:00:00,2023-03-21 18:00:00,2023,3,21,2023,3,21,0,birds
1,1,0,2023-03-21 20:00:00,2023-03-21 21:00:00,2023,3,21,2023,3,21,0,birds
2,1,0,2023-03-22 15:00:00,2023-03-22 21:00:00,2023,3,22,2023,3,22,0,birds
3,1,1,2023-03-21 12:00:00,2023-03-21 13:00:00,2023,3,21,2023,3,21,1,cats
4,1,1,2023-03-24 19:00:00,2023-03-24 21:00:00,2023,3,24,2023,3,24,1,cats
5,2,3,2023-03-03 15:00:00,2023-03-03 16:00:00,2023,3,3,2023,3,3,3,wtf???
6,2,3,2023-03-04 19:00:00,2023-03-04 20:00:00,2023,3,4,2023,3,4,3,wtf???

In [ ]:
merged_df.drop('app_id', axis=1, inplace=True)

In [ ]:
df = merged_df.copy()

In [ ]:
df

,date_begin,date_end,date_begin_year,date_begin_month,date_begin_day,date_end_year,date_end_month,date_end_day,id,name
0,2023-03-21 15:00:00,2023-03-21 18:00:00,2023,3,21,2023,3,21,0,birds
1,2023-03-21 20:00:00,2023-03-21 21:00:00,2023,3,21,2023,3,21,0,birds
2,2023-03-22 15:00:00,2023-03-22 21:00:00,2023,3,22,2023,3,22,0,birds
3,2023-03-21 12:00:00,2023-03-21 13:00:00,2023,3,21,2023,3,21,1,cats
4,2023-03-24 19:00:00,2023-03-24 21:00:00,2023,3,24,2023,3,24,1,cats
5,2023-03-03 15:00:00,2023-03-03 16:00:00,2023,3,3,2023,3,3,3,wtf???
6,2023-03-04 19:00:00,2023-03-04 20:00:00,2023,3,4,2023,3,4,3,wtf???

# База данных

In [ ]:
from sqlite3 import connect

conn = connect('data.db')         # << Создаем подключение к нужной базе данных. (созастся файл)

  Сохраняем датафрейм в базу данных

In [ ]:
df.to_sql('name_table', conn, index=False)

7

тестим ( в работе не нужно)

In [ ]:
query = '''
	SELECT
		*
	FROM
		name_table
'''
df_test = pd.read_sql(query, conn)
df_test

,date_begin,date_end,date_begin_year,date_begin_month,date_begin_day,date_end_year,date_end_month,date_end_day,id,name
0,2023-03-21 15:00:00,2023-03-21 18:00:00,2023,3,21,2023,3,21,0,birds
1,2023-03-21 20:00:00,2023-03-21 21:00:00,2023,3,21,2023,3,21,0,birds
2,2023-03-22 15:00:00,2023-03-22 21:00:00,2023,3,22,2023,3,22,0,birds
3,2023-03-21 12:00:00,2023-03-21 13:00:00,2023,3,21,2023,3,21,1,cats
4,2023-03-24 19:00:00,2023-03-24 21:00:00,2023,3,24,2023,3,24,1,cats
5,2023-03-03 15:00:00,2023-03-03 16:00:00,2023,3,3,2023,3,3,3,wtf???
6,2023-03-04 19:00:00,2023-03-04 20:00:00,2023,3,4,2023,3,4,3,wtf???